// Map languages to their respective country flags
export const getLanguageFlag = (language: string): string => {
  const languageToFlag: Record<string, string> = {
    // Major languages
    "english": "🇺🇸",
    "spanish": "🇪🇸", 
    "french": "🇫🇷",
    "german": "🇩🇪",
    "italian": "🇮🇹",
    "portuguese": "🇵🇹",
    "dutch": "🇳🇱",
    "russian": "🇷🇺",
    "chinese": "🇨🇳",
    "mandarin": "🇨🇳",
    "japanese": "🇯🇵",
    "korean": "🇰🇷",
    "arabic": "🇸🇦",
    "hindi": "🇮🇳",
    "bengali": "🇧🇩",
    "turkish": "🇹🇷",
    "persian": "🇮🇷",
    "farsi": "🇮🇷",
    "urdu": "🇵🇰",
    "thai": "🇹🇭",
    "vietnamese": "🇻🇳",
    "polish": "🇵🇱",
    "czech": "🇨🇿",
    "hungarian": "🇭🇺",
    "romanian": "🇷🇴",
    "bulgarian": "🇧🇬",
    "croatian": "🇭🇷",
    "serbian": "🇷🇸",
    "slovenian": "🇸🇮",
    "slovak": "🇸🇰",
    "greek": "🇬🇷",
    "ukrainian": "🇺🇦",
    "belarusian": "🇧🇾",
    "lithuanian": "🇱🇹",
    "latvian": "🇱🇻",
    "estonian": "🇪🇪",
    "finnish": "🇫🇮",
    "swedish": "🇸🇪",
    "norwegian": "🇳🇴",
    "danish": "🇩🇰",
    "icelandic": "🇮🇸",
    "hebrew": "🇮🇱",
    "swahili": "🇰🇪",
    "amharic": "🇪🇹",
    "yoruba": "🇳🇬",
    "igbo": "🇳🇬",
    "hausa": "🇳🇬",
    "afrikaans": "🇿🇦",
    "zulu": "🇿🇦",
    "xhosa": "🇿🇦",
    "tagalog": "🇵🇭",
    "filipino": "🇵🇭",
    "indonesian": "🇮🇩",
    "malay": "🇲🇾",
    "tamil": "🇮🇳",
    "telugu": "🇮🇳",
    "gujarati": "🇮🇳",
    "marathi": "🇮🇳",
    "punjabi": "🇮🇳",
    "kannada": "🇮🇳",
    "malayalam": "🇮🇳",
    "oriya": "🇮🇳",
    "assamese": "🇮🇳",
    "nepali": "🇳🇵",
    "sinhala": "🇱🇰",
    "burmese": "🇲🇲",
    "khmer": "🇰🇭",
    "lao": "🇱🇦",
    "mongolian": "🇲🇳",
    "kazakh": "🇰🇿",
    "uzbek": "🇺🇿",
    "kyrgyz": "🇰🇬",
    "tajik": "🇹🇯",
    "turkmen": "🇹🇲",
    "azerbaijani": "🇦🇿",
    "armenian": "🇦🇲",
    "georgian": "🇬🇪",
    "albanian": "🇦🇱",
    "macedonian": "🇲🇰",
    "bosnian": "🇧🇦",
    "montenegrin": "🇲🇪",
    "maltese": "🇲🇹",
    "luxembourgish": "🇱🇺",
    "irish": "🇮🇪",
    "welsh": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "scots gaelic": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "basque": "🇪🇸",
    "catalan": "🇪🇸",
    "galician": "🇪🇸",
    "corsican": "🇫🇷",
    "breton": "🇫🇷",
    "occitan": "🇫🇷",
    "sardinian": "🇮🇹",
    "romansh": "🇨🇭",
    "frisian": "🇳🇱",
    "faroese": "🇫🇴",
    "greenlandic": "🇬🇱",
    "maori": "🇳🇿",
    "hawaiian": "🇺🇸",
    "inuktitut": "🇨🇦"
  };
  
  const normalizedLanguage = language.toLowerCase().trim();
  return languageToFlag[normalizedLanguage] || "🌐";
};