/**
 * SUPABASE CLIENT CONFIGURATION
 * 
 * This file sets up the Supabase client for database and authentication operations.
 * Supabase is the backend-as-a-service platform used for:
 * - Database (PostgreSQL) - stores profile data
 * - Authentication - handles user sign-in/sign-out
 * - Storage - for profile pictures and other files
 * - Edge Functions - serverless functions for backend logic
 * 
 * NOTE: This file is automatically generated. Do not edit it directly.
 * The Supabase URL and keys are configured in the Supabase project settings.
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase project URL - points to your Supabase project instance
const SUPABASE_URL = "https://knftyqkhampkqchoncel.supabase.co";

// Supabase anonymous/public key - safe to expose in client-side code
// This key has limited permissions (anon role) and is restricted by Row Level Security policies
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuZnR5cWtoYW1wa3FjaG9uY2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDg4MzYsImV4cCI6MjA2NzAyNDgzNn0.fugiTRvgoD3YqAZPQMV3R6Eu0Wx_9vgE6ZK8zjqFutg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Supabase client instance
 * 
 * This is the main client used throughout the application to:
 * - Query the database (supabase.from('table').select())
 * - Manage authentication (supabase.auth.signIn(), signOut(), etc.)
 * - Call edge functions (supabase.functions.invoke())
 * 
 * Configuration:
 * - storage: Uses browser localStorage to persist sessions
 * - persistSession: Keeps user logged in across page refreshes
 * - autoRefreshToken: Automatically refreshes expired tokens
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,        // Store auth tokens in browser localStorage
    persistSession: true,       // Keep session alive across page refreshes
    autoRefreshToken: true,      // Automatically refresh expired access tokens
  }
});